const fs = require('fs');
const p = 'client/src/modules/warehouse/WarehouseBranchesPage.tsx';
let s = fs.readFileSync(p, 'utf8');
const rep = (a, b) => { if (!s.includes(a)) throw new Error('missing pattern'); s = s.replace(a, b); };
rep("  const submitAction = async () => {\n    if (!confirmAction || !adminPassword.trim()) return;\n    setSubmitting(true);", "  const submitAction = async () => {\n    if (!confirmAction || !adminPassword.trim()) return;\n    const targetBranchId = selectedBranchId;\n    if ((confirmAction === 'create' || confirmAction === 'save') && hasInvalidPhone(form.phone)) {\n      setError('Hotline không hợp lệ. Chỉ dùng số, khoảng trắng, dấu +, -, ., ( ).');\n      return;\n    }\n    setSubmitting(true);");
s = s.replace(/confirmAction === 'save' && selectedBranchId/g, "confirmAction === 'save' && targetBranchId");
s = s.replace(/updateBranch\(selectedBranchId/g, 'updateBranch(targetBranchId');
s = s.replace(/confirmAction === 'set-default' && selectedBranchId/g, "confirmAction === 'set-default' && targetBranchId");
s = s.replace(/setDefaultBranch\(selectedBranchId/g, 'setDefaultBranch(targetBranchId');
s = s.replace(/confirmAction === 'activate' && selectedBranchId/g, "confirmAction === 'activate' && targetBranchId");
s = s.replace(/activateBranch\(selectedBranchId/g, 'activateBranch(targetBranchId');
s = s.replace(/confirmAction === 'deactivate' && selectedBranchId/g, "confirmAction === 'deactivate' && targetBranchId");
s = s.replace(/deactivateBranch\(selectedBranchId/g, 'deactivateBranch(targetBranchId');
s = s.replace(/confirmAction === 'delete' && selectedBranchId/g, "confirmAction === 'delete' && targetBranchId");
s = s.replace(/deleteBranch\(selectedBranchId/g, 'deleteBranch(targetBranchId');
rep("        await loadBranchesData(updated._id);\n        setNotice('Đã lưu thay đổi kho hàng.');", "        setBranches((current) => current.map((branch) => (branch._id === targetBranchId ? updated : branch)));\n        if (selectedBranchIdRef.current === targetBranchId && !isCreateModeRef.current) setForm(mapBranchToForm(updated));\n        setNotice('Đã lưu thay đổi kho hàng.');");
s = s.replace(/usage && selectedBranchId/g, 'usage && targetBranchId');
s = s.replace(/\[selectedBranchId\]: usage/g, '[targetBranchId]: usage');
fs.writeFileSync(p, s, 'utf8');
