<x-ui.layouts::app>
    <div class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-2 align-items-center">
                <div class="col">
                    <h2 class="page-title">
                        {{ __('modules/task::task.gantt') }}
                    </h2>
                </div>
                <div class="col-auto">
                    <div class="btn-list">
                        <a href="{{ route('admin.tasks.index') }}" class="btn btn-white">
                            {!! tabler_icon('list', ['class' => 'icon']) !!}
                            {{ __('modules/task::task.index') }}
                        </a>
                        <a href="{{ route('admin.tasks.kanban') }}" class="btn btn-white">
                            {!! tabler_icon('columns', ['class' => 'icon']) !!}
                            {{ __('modules/task::task.kanban') }}
                        </a>
                        @can('tasks.create')
                            <a href="{{ route('admin.tasks.create') }}" class="btn btn-primary d-flex align-items-center gap-1">
                                {!! tabler_icon('plus', ['class' => 'icon']) !!}
                                {{ __('core/base::general.create') }}
                            </a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="page-body">
        <div class="container-xl" x-data="ganttChart({{ Js::from($tasks) }}, {{ Js::from($projects) }})" x-init="init()">

            {{-- Controls --}}
            <div class="card mb-3">
                <div class="card-body py-2">
                    <div class="row g-3 align-items-end">
                        <div class="col-md-3">
                            <label class="form-label small text-muted mb-1">{{ __('modules/task::task.filter_by_project') }}</label>
                            <select class="form-select form-select-sm" x-model="filterProjectId" @change="render()">
                                <option value="">{{ __('core/base::general.all') }}</option>
                                @foreach ($projects as $project)
                                    <option value="{{ $project->id }}">{{ $project->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label class="form-label small text-muted mb-1">{{ __('modules/task::task.assigned_to') }}</label>
                            <select class="form-select form-select-sm" x-model="filterUserId" @change="render()">
                                <option value="">{{ __('core/base::general.all') }}</option>
                                @foreach ($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-4">
                            <div class="btn-group" role="group">
                                <button class="btn btn-sm" :class="zoomLevel === 'day' ? 'btn-primary' : 'btn-white'" @click="setZoom('day')">{{ trans('modules/task::task.day') }}</button>
                                <button class="btn btn-sm" :class="zoomLevel === 'week' ? 'btn-primary' : 'btn-white'" @click="setZoom('week')">{{ trans('modules/task::task.week') }}</button>
                                <button class="btn btn-sm" :class="zoomLevel === 'month' ? 'btn-primary' : 'btn-white'" @click="setZoom('month')">{{ trans('modules/task::task.month') }}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Gantt Container --}}
            <div class="card">
                <div class="card-body p-0">
                    <div class="gantt-wrapper" x-ref="ganttWrapper">
                        {{-- Gantt content generated by JS --}}
                        <div class="gantt-container" x-ref="ganttContainer">
                            {{-- Task List (sticky left sidebar) --}}
                            <div class="gantt-sidebar" x-ref="sidebar">
                                <div class="gantt-sidebar-header">
                                    <div class="d-flex w-100">
                                        <span class="fw-semibold small" style="width: 60%;">{{ __('modules/task::task.name') }}</span>
                                        <span class="fw-semibold small" style="width: 40%;">{{ __('modules/task::task.assigned_to') }}</span>
                                    </div>
                                </div>
                                <template x-for="task in filteredTasks" :key="task.id">
                                    <div class="gantt-sidebar-row" :title="task.name">
                                        <div class="d-flex w-100">
                                            <span class="text-truncate" style="width: 60%;" x-text="task.name"></span>
                                            <span class="text-truncate text-muted" style="width: 40%; font-size: 0.75rem;" x-text="task.assigned_to || '-'"></span>
                                        </div>
                                    </div>
                                </template>
                            </div>

                            {{-- Timeline Area --}}
                            <div class="gantt-timeline" x-ref="timeline">
                                {{-- Timeline Header --}}
                                <div class="gantt-timeline-header" x-ref="timelineHeader"></div>

                                {{-- Task Rows --}}
                                <div class="gantt-timeline-body" x-ref="timelineBody"></div>

                                {{-- Today Line --}}
                                <div class="gantt-today-line" x-ref="todayLine" x-show="showTodayLine"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @if (count($tasks) === 0)
                <div class="card mt-3">
                    <div class="card-body py-5 text-center">
                        <div class="text-muted">
                            {!! tabler_icon('chart-bar-off', ['class' => 'icon icon-lg mb-2']) !!}
                            <p class="mb-1">{{ trans('modules/task::task.no_tasks_with_dates') }}</p>
                            <p class="text-muted small">{{ trans('modules/task::task.add_date_for_gantt') }}</p>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>

    @push('styles')
        <style>
            .gantt-wrapper {
                overflow: hidden;
                border-radius: 0.375rem;
            }

            .gantt-container {
                display: flex;
                min-height: 300px;
            }

            /* Sidebar */
            .gantt-sidebar {
                min-width: 380px;
                max-width: 380px;
                border-right: 2px solid var(--tblr-border-color);
                background: var(--tblr-bg-surface);
                position: sticky;
                left: 0;
                z-index: 20;
            }

            .gantt-sidebar-header {
                height: 56px;
                padding: 0 1rem;
                display: flex;
                align-items: center;
                border-bottom: 1px solid var(--tblr-border-color);
                background: var(--tblr-bg-surface-secondary, #f8fafc);
            }

            .gantt-sidebar-row {
                height: 40px;
                padding: 0 1rem;
                display: flex;
                align-items: center;
                border-bottom: 1px solid var(--tblr-border-color-translucent);
                font-size: 0.8125rem;
                cursor: default;
                transition: background 0.15s ease;
            }

            .gantt-sidebar-row:hover {
                background: var(--tblr-bg-surface-secondary, #f8fafc);
            }

            /* Timeline */
            .gantt-timeline {
                flex: 1;
                overflow-x: auto;
                position: relative;
            }

            .gantt-timeline-header {
                height: 56px;
                display: flex;
                border-bottom: 1px solid var(--tblr-border-color);
                background: var(--tblr-bg-surface-secondary, #f8fafc);
                position: sticky;
                top: 0;
                z-index: 15;
            }

            .gantt-header-cell {
                display: flex;
                align-items: center;
                justify-content: center;
                border-right: 1px solid var(--tblr-border-color-translucent);
                font-size: 0.7rem;
                font-weight: 500;
                color: var(--tblr-muted);
                user-select: none;
                flex-shrink: 0;
            }

            .gantt-header-cell.is-weekend {
                background: rgba(0, 0, 0, 0.02);
            }

            .gantt-header-cell.is-today {
                background: rgba(var(--tblr-primary-rgb), 0.08);
                color: var(--tblr-primary);
                font-weight: 600;
            }

            .gantt-timeline-body {
                position: relative;
            }

            .gantt-row {
                height: 40px;
                display: flex;
                position: relative;
                border-bottom: 1px solid var(--tblr-border-color-translucent);
            }

            .gantt-row-cell {
                flex-shrink: 0;
                border-right: 1px solid rgba(0, 0, 0, 0.03);
            }

            .gantt-row-cell.is-weekend {
                background: rgba(0, 0, 0, 0.015);
            }

            /* Task Bar */
            .gantt-bar {
                position: absolute;
                height: 24px;
                top: 8px;
                border-radius: 4px;
                display: flex;
                align-items: center;
                font-size: 0.7rem;
                color: white;
                font-weight: 500;
                overflow: hidden;
                cursor: pointer;
                transition: opacity 0.2s ease, transform 0.15s ease;
                z-index: 10;
            }

            .gantt-bar:hover {
                opacity: 0.9;
                transform: scaleY(1.15);
                z-index: 11;
            }

            .gantt-bar-label {
                padding: 0 6px;
                white-space: nowrap;
                text-overflow: ellipsis;
                overflow: hidden;
            }

            .gantt-bar-progress {
                position: absolute;
                left: 0;
                top: 0;
                bottom: 0;
                border-radius: 4px 0 0 4px;
                opacity: 0.3;
                background: rgba(255, 255, 255, 0.4);
            }

            /* Status Colors */
            .gantt-bar--backlog {
                background: #6c757d;
            }

            .gantt-bar--todo {
                background: #4263eb;
            }

            .gantt-bar--in_progress {
                background: #206bc4;
            }

            .gantt-bar--review {
                background: #0ca678;
            }

            .gantt-bar--done {
                background: #2fb344;
            }

            .gantt-bar--overdue {
                background: #cd201f;
            }

            /* Today Line */
            .gantt-today-line {
                position: absolute;
                top: 0;
                bottom: 0;
                width: 2px;
                background: #cd201f;
                z-index: 12;
                pointer-events: none;
            }

            .gantt-today-line::before {
                content: '{{ __('Hôm nay') }}';
                position: absolute;
                top: -24px;
                left: 50%;
                transform: translateX(-50%);
                font-size: 0.65rem;
                color: #cd201f;
                font-weight: 600;
                white-space: nowrap;
            }

            /* Tooltip */
            .gantt-tooltip {
                position: fixed;
                padding: 8px 12px;
                background: rgba(30, 41, 59, 0.95);
                color: white;
                border-radius: 6px;
                font-size: 0.75rem;
                z-index: 1000;
                pointer-events: none;
                max-width: 240px;
                box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
            }

            .gantt-tooltip strong {
                display: block;
                margin-bottom: 4px;
                font-size: 0.8rem;
            }

            .gantt-tooltip .tt-row {
                display: flex;
                justify-content: space-between;
                gap: 12px;
                margin-top: 2px;
            }

            .gantt-tooltip .tt-label {
                color: #94a3b8;
            }
        </style>
    @endpush

    @push('scripts')
        <script>
            function ganttChart(allTasks, allProjects) {
                return {
                    allTasks: allTasks,
                    filteredTasks: [],
                    filterProjectId: '',
                    filterUserId: '',
                    zoomLevel: 'day',
                    showTodayLine: false,
                    cellWidths: {
                        day: 36,
                        week: 120,
                        month: 40
                    },
                    tooltip: null,

                    init() {
                        this.render();
                        // Scroll to today on init
                        this.$nextTick(() => this.scrollToToday());
                    },

                    setZoom(level) {
                        this.zoomLevel = level;
                        this.render();
                        this.$nextTick(() => this.scrollToToday());
                    },

                    render() {
                        // Filter tasks
                        let filtered = [...this.allTasks];

                        if (this.filterProjectId) {
                            filtered = filtered.filter(t => String(t.project_id) === String(this.filterProjectId));
                        }

                        if (this.filterUserId) {
                            filtered = filtered.filter(t => String(t.assigned_to_id) === String(this.filterUserId));
                        }

                        this.filteredTasks = filtered;

                        this.$nextTick(() => this.drawTimeline());
                    },

                    drawTimeline() {
                        if (this.filteredTasks.length === 0) return;

                        const headerEl = this.$refs.timelineHeader;
                        const bodyEl = this.$refs.timelineBody;
                        const todayEl = this.$refs.todayLine;

                        if (!headerEl || !bodyEl) return;

                        // Calculate date range
                        let minDate = null,
                            maxDate = null;
                        this.filteredTasks.forEach(t => {
                            const s = new Date(t.start);
                            const e = new Date(t.end);
                            if (!minDate || s < minDate) minDate = new Date(s);
                            if (!maxDate || e > maxDate) maxDate = new Date(e);
                        });

                        // Add padding
                        minDate.setDate(minDate.getDate() - 3);
                        maxDate.setDate(maxDate.getDate() + 7);

                        const today = new Date();
                        today.setHours(0, 0, 0, 0);

                        const cellWidth = this.cellWidths[this.zoomLevel];
                        const days = this.getDaysBetween(minDate, maxDate);

                        // Draw header
                        let headerHtml = '';
                        if (this.zoomLevel === 'day') {
                            days.forEach(d => {
                                const isWeekend = d.getDay() === 0 || d.getDay() === 6;
                                const isToday = d.getTime() === today.getTime();
                                const cls = (isWeekend ? ' is-weekend' : '') + (isToday ? ' is-today' : '');
                                const label = d.getDate() + '/' + (d.getMonth() + 1);
                                headerHtml += `<div class="gantt-header-cell${cls}" style="width:${cellWidth}px">${label}</div>`;
                            });
                        } else if (this.zoomLevel === 'week') {
                            let weekStart = new Date(minDate);
                            while (weekStart <= maxDate) {
                                const weekEnd = new Date(weekStart);
                                weekEnd.setDate(weekEnd.getDate() + 6);
                                const label = weekStart.getDate() + '/' + (weekStart.getMonth() + 1) + ' - ' + weekEnd.getDate() + '/' + (weekEnd.getMonth() + 1);
                                headerHtml += `<div class="gantt-header-cell" style="width:${cellWidth}px">${label}</div>`;
                                weekStart.setDate(weekStart.getDate() + 7);
                            }
                        } else {
                            let monthDate = new Date(minDate.getFullYear(), minDate.getMonth(), 1);
                            while (monthDate <= maxDate) {
                                const daysInMonth = new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 0).getDate();
                                const w = daysInMonth * cellWidth;
                                const label = (monthDate.getMonth() + 1) + '/' + monthDate.getFullYear();
                                headerHtml += `<div class="gantt-header-cell" style="width:${w}px">${label}</div>`;
                                monthDate.setMonth(monthDate.getMonth() + 1);
                            }
                        }
                        headerEl.innerHTML = headerHtml;

                        // Draw body
                        let bodyHtml = '';
                        const totalWidth = this.zoomLevel === 'day' ?
                            days.length * cellWidth :
                            headerEl.scrollWidth;

                        this.filteredTasks.forEach(task => {
                            let cellsHtml = '';
                            if (this.zoomLevel === 'day') {
                                days.forEach(d => {
                                    const isWeekend = d.getDay() === 0 || d.getDay() === 6;
                                    cellsHtml += `<div class="gantt-row-cell${isWeekend ? ' is-weekend' : ''}" style="width:${cellWidth}px"></div>`;
                                });
                            }

                            // Calculate bar position
                            const taskStart = new Date(task.start);
                            const taskEnd = new Date(task.end);
                            taskStart.setHours(0, 0, 0, 0);
                            taskEnd.setHours(0, 0, 0, 0);

                            let left, width;
                            if (this.zoomLevel === 'day') {
                                const startOffset = Math.round((taskStart - minDate) / 86400000);
                                const duration = Math.max(1, Math.round((taskEnd - taskStart) / 86400000) + 1);
                                left = startOffset * cellWidth;
                                width = duration * cellWidth;
                            } else if (this.zoomLevel === 'week') {
                                const startOffset = (taskStart - minDate) / 86400000;
                                const duration = Math.max(1, (taskEnd - taskStart) / 86400000 + 1);
                                const weekWidth = cellWidth / 7;
                                left = startOffset * weekWidth;
                                width = duration * weekWidth;
                            } else {
                                const startOffset = (taskStart - minDate) / 86400000;
                                const duration = Math.max(1, (taskEnd - taskStart) / 86400000 + 1);
                                left = startOffset * cellWidth;
                                width = duration * cellWidth;
                            }

                            const statusClass = task.is_overdue && task.status !== 'done' ? 'overdue' : task.status;
                            const progress = task.progress || 0;

                            bodyHtml += `<div class="gantt-row">${cellsHtml}`;
                            bodyHtml += `<div class="gantt-bar gantt-bar--${statusClass}"
                                        style="left:${left}px; width:${Math.max(width, cellWidth)}px;"
                                        data-task-id="${task.id}"
                                        data-task-name="${this.escape(task.name)}"
                                        data-task-start="${task.start}"
                                        data-task-end="${task.end}"
                                        data-task-progress="${progress}"
                                        data-task-assignee="${this.escape(task.assigned_to)}"
                                        data-task-project="${this.escape(task.project_name)}"
                                        onmouseenter="ganttTooltipShow(event, this)"
                                        onmouseleave="ganttTooltipHide()">`;
                            if (progress > 0) {
                                bodyHtml += `<div class="gantt-bar-progress" style="width:${progress}%"></div>`;
                            }
                            bodyHtml += `<span class="gantt-bar-label">${this.escape(task.name)}</span>`;
                            bodyHtml += `</div></div>`;
                        });
                        bodyEl.innerHTML = bodyHtml;

                        // Today line
                        if (today >= minDate && today <= maxDate) {
                            this.showTodayLine = true;
                            let todayLeft;
                            if (this.zoomLevel === 'day') {
                                todayLeft = Math.round((today - minDate) / 86400000) * cellWidth + cellWidth / 2;
                            } else if (this.zoomLevel === 'week') {
                                todayLeft = ((today - minDate) / 86400000) * (cellWidth / 7);
                            } else {
                                todayLeft = ((today - minDate) / 86400000) * cellWidth;
                            }
                            todayEl.style.left = todayLeft + 'px';
                        } else {
                            this.showTodayLine = false;
                        }
                    },

                    scrollToToday() {
                        const timeline = this.$refs.timeline;
                        const todayLine = this.$refs.todayLine;
                        if (timeline && todayLine && this.showTodayLine) {
                            const todayLeft = parseInt(todayLine.style.left, 10);
                            timeline.scrollLeft = Math.max(0, todayLeft - timeline.clientWidth / 3);
                        }
                    },

                    getDaysBetween(start, end) {
                        const days = [];
                        const current = new Date(start);
                        while (current <= end) {
                            days.push(new Date(current));
                            current.setDate(current.getDate() + 1);
                        }
                        return days;
                    },

                    escape(str) {
                        if (!str) return '';
                        const div = document.createElement('div');
                        div.appendChild(document.createTextNode(str));
                        return div.innerHTML;
                    }
                };
            }

            // Tooltip functions (global)
            let _ganttTooltip = null;

            function ganttTooltipShow(event, el) {
                if (!_ganttTooltip) {
                    _ganttTooltip = document.createElement('div');
                    _ganttTooltip.className = 'gantt-tooltip';
                    document.body.appendChild(_ganttTooltip);
                }
                const name = el.dataset.taskName;
                const start = el.dataset.taskStart;
                const end = el.dataset.taskEnd;
                const progress = el.dataset.taskProgress;
                const assignee = el.dataset.taskAssignee;
                const project = el.dataset.taskProject;

                _ganttTooltip.innerHTML = `
                <strong>${name}</strong>
                ${project ? `<div class="tt-row"><span class="tt-label">Dự án:</span><span>${project}</span></div>` : ''}
                <div class="tt-row"><span class="tt-label">Bắt đầu:</span><span>${start}</span></div>
                <div class="tt-row"><span class="tt-label">Kết thúc:</span><span>${end}</span></div>
                <div class="tt-row"><span class="tt-label">Tiến độ:</span><span>${progress}%</span></div>
                ${assignee ? `<div class="tt-row"><span class="tt-label">Thực hiện:</span><span>${assignee}</span></div>` : ''}
            `;

                const rect = el.getBoundingClientRect();
                _ganttTooltip.style.display = 'block';
                _ganttTooltip.style.left = (rect.left + rect.width / 2 - _ganttTooltip.offsetWidth / 2) + 'px';
                _ganttTooltip.style.top = (rect.top - _ganttTooltip.offsetHeight - 8) + 'px';
            }

            function ganttTooltipHide() {
                if (_ganttTooltip) _ganttTooltip.style.display = 'none';
            }
        </script>
    @endpush
</x-ui.layouts::app>
